(function () {
  const key = 'grown-cart'; let items = JSON.parse(localStorage.getItem(key) || '[]'); const root = document.getElementById('cart-root');
  const DEAL_QTY = 2; const DEAL_PRICE = 5;
  const money = n => `$${n.toFixed(2)}`;
  const lineTotal = item => Math.floor(item.quantity / DEAL_QTY) * DEAL_PRICE + (item.quantity % DEAL_QTY) * item.price;
  const save = () => { localStorage.setItem(key, JSON.stringify(items)); render(); };
  function render() { const count = items.reduce((n,item) => n + item.quantity, 0); document.querySelectorAll('[data-cart-count]').forEach(el => el.textContent = count); const subtotal = items.reduce((n,item) => n + lineTotal(item), 0); root.innerHTML = `<div class="cart-backdrop" hidden></div><aside class="cart-drawer" id="cart-drawer" aria-label="Shopping cart" aria-hidden="true"><div class="cart-head"><span>cart (${count})</span><button class="cart-close" type="button">close</button></div><div>${items.length ? items.map((item,i) => `<div class="cart-item"><img src="${item.image}" alt=""><div><p>${item.name}</p><p>${item.quantity} &times; ${money(item.price)} &middot; ${money(lineTotal(item))}</p></div><button class="remove" data-remove="${i}">remove</button></div>`).join('') : '<p>the cart is empty</p>'}</div><div class="cart-footer"><span>subtotal</span> <span style="float:right">${money(subtotal)}</span><button class="checkout" type="button" ${items.length ? '' : 'disabled'}>checkout</button></div></aside>`; root.querySelector('.cart-close').onclick = close; root.querySelector('.cart-backdrop').onclick = close; root.querySelectorAll('[data-remove]').forEach(b => b.onclick = () => { items.splice(Number(b.dataset.remove),1); save(); }); root.querySelector('.checkout').onclick = () => alert('Stripe Checkout will be connected here. No payment details are collected by this site yet.'); }
  function open() { root.querySelector('.cart-drawer').classList.add('open'); root.querySelector('.cart-drawer').setAttribute('aria-hidden','false'); root.querySelector('.cart-backdrop').hidden = false; document.querySelector('.cart-toggle').setAttribute('aria-expanded','true'); }
  function close() { root.querySelector('.cart-drawer').classList.remove('open'); root.querySelector('.cart-drawer').setAttribute('aria-hidden','true'); root.querySelector('.cart-backdrop').hidden = true; document.querySelector('.cart-toggle').setAttribute('aria-expanded','false'); }
  window.cart = { add(product,quantity) { const item = items.find(item => item.slug === product.slug); if (item) item.quantity += quantity; else items.push({...product,quantity}); save(); }, open }; document.querySelector('.cart-toggle').addEventListener('click', open); render();
})();
